package edu.ntnu.irr.bidata.Model.SnakesAndLadders.Event;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * Abstract class for different types of events in SnakesAndLadders.
 *
 * <p>This class uses Jackson annotations to support polymorphic deserialization.
 * It allows the system to dynamically determine the specific subclass of an event
 * during JSON (de)serialization based on the "@class" property.</p>
 * 
 * <p>I used Chat GTP to find out how i shold use the Jackson libery to suport
 * polymorphic deserialization, and i based the JasonTypeInfo and JsonSubTypes
 * on code generated by chat GTP</p>
 *
 * <p>Known subclasses:</p>
 * <ul>
 *   <li>{@link LadderEvent}</li>
 *   <li>{@link QuizEvent}</li>
 * </ul>
 */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.CLASS, // Use the fully qualified class name as the type identifier
    include = JsonTypeInfo.As.PROPERTY, // Include type information as a property in JSON
    property = "@class" // The property name that holds the class info in JSON
)
@JsonSubTypes({
    @JsonSubTypes.Type(value = LadderEvent.class, name = "LadderEvent"), // Register LadderEvent as a subtype
    @JsonSubTypes.Type(value = QuizEvent.class, name = "QizzEvent") // Register QizzEvent as a subtype
})

public abstract class Event {
  /**
   * Represents the action that should be performed when this event is triggered.
   *
   * @return an integer representing the tile the player is moved to.
   */
  public abstract int action(); // Abstract method to be implemented by subclasses
}